import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // Generated by `wrangler types`; keep wrangler output as-is.
    ignorePatterns: ["**/worker-configuration.d.ts"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    // @cloudflare/vitest-pool-workers peers vitest 3.x; vite-plus/test is vitest 4.
    overrides: [
      {
        files: ["apps/api/test/workers/**"],
        rules: { "vite-plus/prefer-vite-plus-imports": "off" },
      },
    ],
  },
  run: {
    cache: true,
  },
});
