import { defineConfig } from "vite-plus";

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  fmt: {
    // Generated by `wrangler types`; keep wrangler output as-is.
    ignorePatterns: ["**/worker-configuration.d.ts"],
  },
  lint: {
    jsPlugins: [{ name: "vite-plus", specifier: "vite-plus/oxlint-plugin" }],
    rules: { "vite-plus/prefer-vite-plus-imports": "error" },
    options: { typeAware: true, typeCheck: true },
    // @cloudflare/vitest-pool-workers peers vitest 3.x; vite-plus/test is vitest 4.
    overrides: [
      {
        files: ["apps/api/test/workers/**"],
        rules: { "vite-plus/prefer-vite-plus-imports": "off" },
      },
    ],
  },
  run: {
    cache: true,
    tasks: {
      builds: {
        cache: false,
        command: 'node -e ""',
        dependsOn: [
          "@uinaf/attach-api#build",
          "@uinaf/attach-cli#build",
          "@uinaf/attach-shared#build",
        ],
      },
      checks: {
        cache: false,
        command: 'node -e ""',
        dependsOn: ["design", "format", "lint", "types"],
      },
      design: "vp run @uinaf/attach-web#design:check",
      format: "vp fmt --check",
      lint: "vp lint",
      ready: {
        cache: false,
        command: 'node -e ""',
        dependsOn: ["builds", "design", "format", "lint", "tests", "types"],
      },
      tests: {
        cache: false,
        command: 'node -e ""',
        dependsOn: [
          "@uinaf/attach-api#test",
          "@uinaf/attach-cli#test",
          "@uinaf/attach-shared#test",
        ],
      },
      types: "pnpm --filter @uinaf/attach-api types:check",
    },
  },
});
