/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: c25101a7d1f2571c53d573964a9171c7)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_CLIENT_SECRET: string;
	AGENT_REGISTRY: string;
	ALLOWED_GITHUB_USER_IDS: string;
	ATTACH_PUBLIC_BASE: string;
	JTI: DurableObjectNamespace<import("./src/index").JtiStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "JtiStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_CLIENT_SECRET" | "AGENT_REGISTRY" | "ALLOWED_GITHUB_USER_IDS" | "ATTACH_PUBLIC_BASE">> {}
}
