/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: d04be35c1e919f81b5277a7f9078e561)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	ALLOWED_GITHUB_USER_IDS: string;
	ATTACH_PUBLIC_BASE: string;
	GITHUB_APP_CLIENT_ID: string;
	GITHUB_APP_CLIENT_SECRET: string;
	JTI: DurableObjectNamespace<import("./src/index").JtiStore>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "JtiStore";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_GITHUB_USER_IDS" | "ATTACH_PUBLIC_BASE" | "GITHUB_APP_CLIENT_ID" | "GITHUB_APP_CLIENT_SECRET">> {}
}
